config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'page#home'

  resources :items
  resources :lists
  get 'page/home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :itemizes
  has_many :lists, through: :itemizes
end

app/models/itemize.rb
class Itemize < ApplicationRecord
  belongs_to :item
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :itemizes
  has_many :items, through: :itemizes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.all
    @item = Item.new
  end

  def create
    @item = Item.new(params.require(:item).permit(:name))
    @item.save
    flash.notice = "'#{@item.name}' was added!"
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash.notice = "'#{@item.name}' was Deleted!"
    redirect_to items_path
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(name: params[:list][:name])
    @list.save
    flash.notice = "New list '#{@list.name}' created!"
    redirect_to list_path(@list)
  end

  def edit
    @list = List.find(params[:id])
    @items = Item.all
  end

  def update
    @list = List.find(params[:id])
    @items = Item.all
    flash.notice = "Updated!"
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    flash.notice = "'#{@list.name}' was Deleted!"
    redirect_to lists_path
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!
  
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/items/index.html.erb
<h1>All Items</h1>
<%= form_for(@item, html: {multipart: true}) do |f| %>
<ul>
  <% @item.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %> <%= f.submit "", :type => :image, :src => "/images/add.jpg" %>
  </p>
<% end %>
<br />

<div class="column" id="available-items">
  <% @items.each do |item| %>
      <% item_id = item.id.to_s %>
      <div class="portlet" id=<%=item_id%>>
        <div class="portlet-header"><%=item.name%>  <div class="item-delete-button"><%= link_to image_tag("delete.jpg", size: "40x40", alt: "delete"), item_path(item), method: :delete %></div></div>
        <div class="portlet-content"><%=item.note%></div>

      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grocerymate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
    <header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="login">
        <% if user_signed_in? %>
          <p>Hello, <%=current_user.email %></p>
        <% else %>
          <p>Sign-In</p>
        <% end %>
      </div>
      <div class="nav-button">
        <%= link_to image_tag("hamburger.jpg", size: "50x50", alt: "Menu"), lists_path %>
      </div>
      <div class="nav">
        <ul>
          <li><%= link_to "Lists", lists_path %></li>
          <li><%= link_to "Items", items_path %></li>
          <li><a href="#">Account</a></li>
        </ul>
      </div>
    </header>
    <div class="content">
      <%= yield %>
    </div>
    <footer>
    </footer>
  </div>
  </body>
</html>

app/views/lists/edit.html.erb
<h1><%= @list.name %></h1>
<h2>=Editing=</h2>

<div class="column" id="current-list">
  <h3>I need...</h3>
  <% @list.items.each do |item| %>
    <% item_id = item.id.to_s %>
    <div class="portlet" id=<%=item_id%>>
      <div class="portlet-header">item.name</div>
      <div class="portlet-content">item.note</div>
    </div>
  <% end %>
</div>

<div class="column" id="available-items">
  <h3>Items...</h3>

  <% @items.each do |item| %>
    <% if not @list.items.exists?(item) %>
      <% item_id = item.id.to_s %>
      <div class="portlet" id=<%=item_id%>>
        <div class="portlet-header"><%=item.name%></div>
        <div class="portlet-content"><%=item.note%></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/index.html.erb
<h1>All Lists</h1>
<%= link_to "New List", new_list_path %><br /><br />

<% @lists.each do |list| %>
<div class = "list-name">
  <%= link_to list.name, list_path(list) %>
  <%= link_to "Edit", edit_list_path(list) %>
  <%= link_to image_tag("delete.jpg", size: "40x40", alt: "delete"), list_path(list), method: :delete, class: "right-sided" %><br />
</div>
<%end%>

app/views/lists/new.html.erb
<%= form_for(@list, html: {multipart: true}) do |f| %>
<ul>
  <% @list.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/lists/show.html.erb
<h1><%=@list.name%></h1>
<h2>=Shopping=</h2>

<div class="column-container">
  <h3>I need...</h3>
  <div class="column">
    <% @list.items.each do |item| %>
      <div class="portlet">
        <div class="portlet-header">item.name</div>
        <div class="portlet-content">item.note</div>
      </div>
    <% end %>
  </div>
</div>

<div class="column-container">
  <h3>I have...</h3>
  <div class="column">

    <div class="portlet">
      <div class="portlet-header">Links</div>
      <div class="portlet-content">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</div>
    </div>
  </div>
</div>

app/views/page/home.html.erb
<h1>Home Page</h1>
<p>Nothing to see here...</p>